language: node_js
env:
  matrix:
  - NODE_OPTIONS=--max_old_space_size=4096
  global:
node_js:
- '10'
sudo: false
install:
- yarn
script:
- yarn build || travis_terminate 1
deploy:
  - provider: firebase
    on: master
    skip_cleanup: true
    token:
      secure: wMeqSja96P+MCYb7A8D29HVb9/dhBms5CWk+fwbVdKruJmV9sIow6L7iCWWdQupyv0Up/01yeP6UezccrgrxzUYEH9Bl8fMUjDkCmeahHLVTUB3C2cnSam0xKQZZvtHAEDsoMBZwzBLjtgoBC+VkltuVWDQ/UHIr9x+KPO9GZIKMSPlFultz8CLQNmnfCODvzCkGeVXzv2nFJvtvHXbfULlgbE3MEb0/WPzHxgzYnieUs/tQwtuZnb+GRbZW4mAJSkF2UZn5yNtA60Y7qDSyemi0I1g5aRhbXM+jnOu6uO6/BHnvIUcdLEVokbwJ9NIwMBUWK3LRS2epcBcCtC1S6r+GY5twT3+eZIiwp+haNgUoE7A4k1+wNv9NxxNtkK5bL3n2ZntKpyxMcadZfC8mp6mobRtuWPh4hj+pLDm24XWyCM8o83h3OZSYisVxvTD7Jazn6TNnEeYNUWLdf5tjGJ180mTjbqv5OT0sQgAcGd3XNgB1EqJOjDJ7ix+fjSgBcpoDn2JMqMgEMulPi6aGQVLJfwDQzeEngAUXqwLnwM9OFrhvoAOwkFe0A6a9IdAW4XQUVwXyzY53zcZkakVEBXM1muMtVvjZsi5uLSI1MYfHX3fhbj2XQm8m2YahiJiwySvKMUL51kpoVcG0/FahLJ0CuRq26kD7Y+oKNJ8JwDw=
    project: "chatbot-cognite-demo"